---
version: '3'
networks:
  net:
    driver: bridge
services:
  nest-api:
    image: marcoshssilva-nestjs-example-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - "3000:3000"
    environment:
    - POSTGRES_HOST=postgres
    - POSTGRES_PORT=5432
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=db_nestjs_example
    depends_on:
    - postgres
    networks:
    - net
  postgres:
    image: postgres:13
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=db_nestjs_example
    networks:
    - net